---
# control
control:
  data_name: MNIST
  model_name: linear
# experiment
pin_memory: True
num_worker: 0
init_seed: 0
num_experiment: 1
log_interval: 0.25
device: cuda
resume_mode: 0
verbose: False
